// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/profile/api/data_sources/profile_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:tracking_app/features/profile/api/api_client/profile_api_client.dart'
    as _i3;
import 'package:tracking_app/features/profile/data/models/profile_data_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfileDataModel_0 extends _i1.SmartFake
    implements _i2.ProfileDataModel {
  _FakeProfileDataModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileApiClient extends _i1.Mock implements _i3.ProfileApiClient {
  MockProfileApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(this, Invocation.method(#logout, [])),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i2.ProfileDataModel> getProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, []),
            returnValue: _i4.Future<_i2.ProfileDataModel>.value(
              _FakeProfileDataModel_0(
                this,
                Invocation.method(#getProfileData, []),
              ),
            ),
          )
          as _i4.Future<_i2.ProfileDataModel>);
}

/// A class which mocks [ProfileDataModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileDataModel extends _i1.Mock implements _i2.ProfileDataModel {
  MockProfileDataModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i5.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get firstName =>
      (super.noSuchMethod(
            Invocation.getter(#firstName),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#firstName),
            ),
          )
          as String);

  @override
  String get lastName =>
      (super.noSuchMethod(
            Invocation.getter(#lastName),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#lastName),
            ),
          )
          as String);

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get gender =>
      (super.noSuchMethod(
            Invocation.getter(#gender),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#gender),
            ),
          )
          as String);

  @override
  String get phone =>
      (super.noSuchMethod(
            Invocation.getter(#phone),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#phone),
            ),
          )
          as String);

  @override
  String get photo =>
      (super.noSuchMethod(
            Invocation.getter(#photo),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#photo),
            ),
          )
          as String);

  @override
  String get role =>
      (super.noSuchMethod(
            Invocation.getter(#role),
            returnValue: _i5.dummyValue<String>(this, Invocation.getter(#role)),
          )
          as String);

  @override
  List<dynamic> get wishlist =>
      (super.noSuchMethod(
            Invocation.getter(#wishlist),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  List<dynamic> get addresses =>
      (super.noSuchMethod(
            Invocation.getter(#addresses),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  String get createdAt =>
      (super.noSuchMethod(
            Invocation.getter(#createdAt),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#createdAt),
            ),
          )
          as String);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
