// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/profile/data/repo/profile_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tracking_app/config/base_response/base_response.dart' as _i4;
import 'package:tracking_app/features/profile/data/data_sources/profile_remote_data_source_contract.dart'
    as _i2;
import 'package:tracking_app/features/profile/data/models/profile_data_model.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProfileRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDataSourceContract extends _i1.Mock
    implements _i2.ProfileRemoteDataSourceContract {
  MockProfileRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.ProfileDataModel>> getProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.ProfileDataModel>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.ProfileDataModel>>(
                    this,
                    Invocation.method(#getProfileData, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.ProfileDataModel>>);

  @override
  _i3.Future<_i4.BaseResponse<String>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<_i4.BaseResponse<String>>.value(
              _i6.dummyValue<_i4.BaseResponse<String>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<String>>);
}
