// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEE4weQurlra1PhZFreVfPmvS9RKvpZAA',
    appId: '1:685078061318:web:1d10596f60be58b8de3e87',
    messagingSenderId: '685078061318',
    projectId: 'track-app-d33ab',
    authDomain: 'track-app-d33ab.firebaseapp.com',
    storageBucket: 'track-app-d33ab.firebasestorage.app',
    measurementId: 'G-58PRQ07DJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMpJ9T50h9c9rMqUYaB7zxqZ2-FPYOxRo',
    appId: '1:685078061318:android:f075dba71bb5e0e5de3e87',
    messagingSenderId: '685078061318',
    projectId: 'track-app-d33ab',
    storageBucket: 'track-app-d33ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4II6MAekPplmIqgQf10tGPZFysy2Kji4',
    appId: '1:685078061318:ios:e926b5d0e84b51c5de3e87',
    messagingSenderId: '685078061318',
    projectId: 'track-app-d33ab',
    storageBucket: 'track-app-d33ab.firebasestorage.app',
    iosBundleId: 'com.example.trackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4II6MAekPplmIqgQf10tGPZFysy2Kji4',
    appId: '1:685078061318:ios:e926b5d0e84b51c5de3e87',
    messagingSenderId: '685078061318',
    projectId: 'track-app-d33ab',
    storageBucket: 'track-app-d33ab.firebasestorage.app',
    iosBundleId: 'com.example.trackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEE4weQurlra1PhZFreVfPmvS9RKvpZAA',
    appId: '1:685078061318:web:8843d1434f60a03dde3e87',
    messagingSenderId: '685078061318',
    projectId: 'track-app-d33ab',
    authDomain: 'track-app-d33ab.firebaseapp.com',
    storageBucket: 'track-app-d33ab.firebasestorage.app',
    measurementId: 'G-8FWTWC6318',
  );
}
