// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/profile/presentation/view_model/profile_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tracking_app/config/base_response/base_response.dart' as _i5;
import 'package:tracking_app/features/profile/domain/entities/profile_data_entity.dart'
    as _i8;
import 'package:tracking_app/features/profile/domain/repo/profile_repo_contract.dart'
    as _i2;
import 'package:tracking_app/features/profile/domain/use_cases/get_profile_data_use_case.dart'
    as _i7;
import 'package:tracking_app/features/profile/domain/use_cases/logout_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfileRepoContract_0 extends _i1.SmartFake
    implements _i2.ProfileRepoContract {
  _FakeProfileRepoContract_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i3.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepoContract get profileRepoContract =>
      (super.noSuchMethod(
            Invocation.getter(#profileRepoContract),
            returnValue: _FakeProfileRepoContract_0(
              this,
              Invocation.getter(#profileRepoContract),
            ),
          )
          as _i2.ProfileRepoContract);

  @override
  _i4.Future<_i5.BaseResponse<String>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.BaseResponse<String>>.value(
              _i6.dummyValue<_i5.BaseResponse<String>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.BaseResponse<String>>);
}

/// A class which mocks [GetProfileDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileDataUseCase extends _i1.Mock
    implements _i7.GetProfileDataUseCase {
  MockGetProfileDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepoContract get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProfileRepoContract_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ProfileRepoContract);

  @override
  _i4.Future<_i5.BaseResponse<_i8.ProfileDataEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i8.ProfileDataEntity>>.value(
                  _i6.dummyValue<_i5.BaseResponse<_i8.ProfileDataEntity>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i8.ProfileDataEntity>>);
}

/// A class which mocks [ProfileDataEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileDataEntity extends _i1.Mock implements _i8.ProfileDataEntity {
  MockProfileDataEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get firstName =>
      (super.noSuchMethod(
            Invocation.getter(#firstName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#firstName),
            ),
          )
          as String);

  @override
  String get lastName =>
      (super.noSuchMethod(
            Invocation.getter(#lastName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lastName),
            ),
          )
          as String);

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get phone =>
      (super.noSuchMethod(
            Invocation.getter(#phone),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#phone),
            ),
          )
          as String);

  @override
  String get photo =>
      (super.noSuchMethod(
            Invocation.getter(#photo),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#photo),
            ),
          )
          as String);

  @override
  String get gender =>
      (super.noSuchMethod(
            Invocation.getter(#gender),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#gender),
            ),
          )
          as String);

  @override
  String get fullName =>
      (super.noSuchMethod(
            Invocation.getter(#fullName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#fullName),
            ),
          )
          as String);
}
