// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/edit_profile/presentation/view_model/cubit/edit_profile_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:tracking_app/config/base_response/base_response.dart' as _i5;
import 'package:tracking_app/features/edit_profile/domain/entities/edit_profile_response_entity.dart'
    as _i6;
import 'package:tracking_app/features/edit_profile/domain/repositories/edit_profile_repository.dart'
    as _i2;
import 'package:tracking_app/features/edit_profile/domain/use_cases/edit_profile_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEditProfileRepository_0 extends _i1.SmartFake
    implements _i2.EditProfileRepository {
  _FakeEditProfileRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EditProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileUseCase extends _i1.Mock
    implements _i3.EditProfileUseCase {
  MockEditProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EditProfileRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeEditProfileRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.EditProfileRepository);

  @override
  _i4.Future<_i5.BaseResponse<_i6.EditProfileResponseEntity>> call({
    required String? firstName,
    required String? lastName,
    required String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #firstName: firstName,
              #lastName: lastName,
              #phone: phone,
            }),
            returnValue:
                _i4.Future<
                  _i5.BaseResponse<_i6.EditProfileResponseEntity>
                >.value(
                  _i7.dummyValue<
                    _i5.BaseResponse<_i6.EditProfileResponseEntity>
                  >(
                    this,
                    Invocation.method(#call, [], {
                      #firstName: firstName,
                      #lastName: lastName,
                      #phone: phone,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.EditProfileResponseEntity>>);
}
